- clean: [
    '~'
]

- link:
    ~/.tmux.conf: tmux.conf
    ~/.tmux: tmux

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [~/.tmux/plugins/tpm/scripts/install_plugins.sh >/dev/null 2>&1, Installing tmux plugins]

