- clean: [
    '~'
]

- link:
    ~/.config/i3: i3
    ~/.config/polybar: polybar
    ~/.tmux.conf: tmux.conf
    ~/.tmux: tmux
    ~/.config/kitty: kitty
    ~/.config/nvim: nvim
    ~/.config/fish: fish
    ~/.config/starship.toml: starship.toml
    ~/.config/atuin: atuin

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [~/.tmux/plugins/tpm/scripts/install_plugins.sh >/dev/null 2>&1, Installing tmux plugins]

